<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDsAImvJ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDsAImvJ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDsAImvJ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDsAImvJ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDsAImvJ\appAppKernelProdContainer([
    'container.build_hash' => 'DsAImvJ',
    'container.build_id' => '98611385',
    'container.build_time' => 1721207446,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDsAImvJ');
