<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXduV6xV\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXduV6xV/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXduV6xV.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXduV6xV\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXduV6xV\appAppKernelProdContainer([
    'container.build_hash' => 'XduV6xV',
    'container.build_id' => '09b630ef',
    'container.build_time' => 1721207519,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXduV6xV');
